name: .Net Core Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dotnet-core-tests:
    name: ${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}
    runs-on: ubuntu-24.04-arm
    
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
        objectPooling:
          - {
              name: Pool_Enabled,
              symbol: PROTO_PROMISE_POOL_ENABLE
            }
          - {
              name: Pool_Disabled,
              symbol: PROTO_PROMISE_POOL_DISABLE
            }
        devMode:
          - {
              name: devMode,
              value: true
            }
          - {
              name: userMode,
              value: false
            }

        exclude:
          # DEBUG mode forces pooling disabled.
          - {
              config: Debug,
              objectPooling: { name: Pool_Enabled }
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.X
          
      - name: Run Analyzer Tests
        run: |
          dotnet test ./Tests/ProtoPromise.Tests.Analyzer/ProtoPromise.Tests.Analyzer.csproj -c ${{ matrix.config }} -f net8.0 --logger "Console;Verbosity=normal" --logger "trx;logfilename=dotnet-test-results-net8.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}-analyzer.trx" -p:ExtraDefineConstants=${{ matrix.objectPooling.symbol }} -p:DeveloperMode=${{ matrix.devMode.value }} --results-directory "./TestResults"
        timeout-minutes: 10
          
      - name: Run Core Tests
        run: |
          dotnet test ./Tests/ProtoPromise.Tests/ProtoPromise.Tests.csproj -c ${{ matrix.config }} -f net8.0 --logger "Console;Verbosity=normal" --logger "trx;logfilename=dotnet-test-results-net8.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}-core.trx" -p:ExtraDefineConstants=${{ matrix.objectPooling.symbol }} -p:DeveloperMode=${{ matrix.devMode.value }} --results-directory "./TestResults"
        timeout-minutes: 180

      - uses: dorny/test-reporter@v2
        if: always()
        with:
          name: dotnet-test-results-net8.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}
          path: TestResults/*.trx
          reporter: dotnet-trx

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dotnet-test-results-net8.0-${{ matrix.config }}-${{ matrix.objectPooling.name }}-${{ matrix.devMode.name }}
          path: TestResults
