# This workflow is to make sure builds work properly in all runtimes and with all configurations.
# This is done because WebGL is currently not possible to run platform tests in cloud CI.
# Only building for WebGL because it does the full IL2CPP process plus an extra emscripten process.
# Standalone is built in IL2CPP tests, and other platforms do the same IL2CPP process.
# We do not need to test Mono builds here because that is already done with the Editor tests.

name: Unity WebGL Builds

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.mode.name }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        mode:
          - {
              name: Release,
              symbol: PROTO_PROMISE_DEBUG_DISABLE
            }
          - {
              name: Debug,
              symbol: PROTO_PROMISE_DEBUG_ENABLE
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rewrite ProjectSettings
        run: |
          DefineSymbols="${{ matrix.mode.symbol }}"
          DefineOriginal="  scriptingDefineSymbols: {}"
          DefineReplace="  scriptingDefineSymbols: \\n    13: $DefineSymbols"
          sed -i "{s/$DefineOriginal/$DefineReplace/g}" ProtoPromise_Unity/ProjectSettings/ProjectSettings.asset

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2018_4_36F1_UBUNTU }}
        with:
          projectPath: ProtoPromise_Unity
          targetPlatform: WebGL
          allowDirtyBuild: true
        timeout-minutes: 90